name: 'SecretSync'
description: 'Universal secrets synchronization pipeline for multi-cloud secret management with Vault, AWS, GCP, and more'
author: 'jbcom'

branding:
  icon: 'lock'
  color: 'blue'

inputs:
  config:
    description: 'Path to the SecretSync configuration file (YAML)'
    required: false
    default: 'config.yaml'
  
  targets:
    description: 'Comma-separated list of targets to sync (leave empty for all targets)'
    required: false
    default: ''
  
  dry-run:
    description: 'Run in dry-run mode (no changes will be made)'
    required: false
    default: 'false'
  
  merge-only:
    description: 'Only run the merge phase (skip AWS sync)'
    required: false
    default: 'false'
  
  sync-only:
    description: 'Only run the sync phase (skip merge)'
    required: false
    default: 'false'
  
  discover:
    description: 'Enable dynamic target discovery from AWS Organizations/Identity Center'
    required: false
    default: 'false'
  
  output-format:
    description: 'Output format for diff/results (human, json, github, compact)'
    required: false
    default: 'github'
  
  compute-diff:
    description: 'Compute and show diff even when not in dry-run mode'
    required: false
    default: 'false'
  
  exit-code:
    description: 'Use exit codes for CI/CD (0=no changes, 1=changes, 2=errors)'
    required: false
    default: 'false'
  
  log-level:
    description: 'Log level (debug, info, warn, error)'
    required: false
    default: 'info'
  
  log-format:
    description: 'Log format (text, json)'
    required: false
    default: 'text'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'pipeline'
    - '--config'
    - ${{ inputs.config }}
    - ${{ inputs.targets != '' && format('--targets={0}', inputs.targets) || '' }}
    - ${{ inputs.dry-run == 'true' && '--dry-run' || '' }}
    - ${{ inputs.merge-only == 'true' && '--merge-only' || '' }}
    - ${{ inputs.sync-only == 'true' && '--sync-only' || '' }}
    - ${{ inputs.discover == 'true' && '--discover' || '' }}
    - '--output'
    - ${{ inputs.output-format }}
    - ${{ inputs.compute-diff == 'true' && '--diff' || '' }}
    - ${{ inputs.exit-code == 'true' && '--exit-code' || '' }}
    - '--log-level'
    - ${{ inputs.log-level }}
    - '--log-format'
    - ${{ inputs.log-format }}
