name: Feature Request
description: Suggest a new feature or enhancement for SecretSync
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        As a [role], I want [feature] so that [benefit].
        
        Currently, I have to [current workaround] which is [pain point].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work? What should the user experience be?
      placeholder: |
        I would like SecretSync to...
        
        The configuration would look like:
        ```yaml
        # example config
        ```
        
        The CLI usage would be:
        ```bash
        secretsync new-command --flag value
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered? What workarounds exist today?
      placeholder: |
        - Alternative 1: [description and why it's not ideal]
        - Alternative 2: [description and why it's not ideal]
        - Current workaround: [what you do today]

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
        - Critical - Cannot use SecretSync without this
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: What area of SecretSync does this affect?
      options:
        - Core Pipeline
        - Secret Stores (Vault, AWS, etc.)
        - Discovery (AWS Organizations, Identity Center)
        - Diff/Output
        - CLI/UX
        - GitHub Action
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples that would help?
      placeholder: |
        - Links to similar features in other tools
        - Screenshots or mockups
        - Example configurations
        - Performance considerations

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have considered if this could be solved with existing features
          required: true
        - label: I have provided a clear use case and benefit
          required: true