name: Question
description: Ask a question about SecretSync usage or configuration
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about SecretSync? We're here to help!
        
        **💡 Tip**: For general discussions, consider using [GitHub Discussions](https://github.com/jbcom/secretsync/discussions) instead.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What type of question is this?
      options:
        - Configuration Help
        - Deployment/Setup
        - Troubleshooting
        - Best Practices
        - Feature Clarification
        - Integration Help
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to accomplish? What have you tried so far?
      placeholder: |
        I'm trying to...
        
        I've already tried...
        
        My current setup is...

  - type: textarea
    id: config
    attributes:
      label: Configuration (if relevant)
      description: Your SecretSync configuration (sanitized)
      render: yaml
      placeholder: |
        # Only include if relevant to your question
        # Remove all secrets/credentials
        vault:
          address: "https://vault.example.com"

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have read the relevant documentation
          required: true
        - label: I have removed any sensitive information
          required: true